### PR TITLE
Rename SmileID Interfaces

### PR DESCRIPTION
**Pull request by jumaallan**
Story: N/A

## Summary

This PR renames the public SmileID interface to match Android one, and make it uniform when implementing them on the cross platform  SDKs

## Known Issues

Any shortcomings in your work. This may include corner cases not correctly handled or issues related
to but not within the scope of your PR. Design compromises should be discussed here if they were not
already discussed above.

## Test Instructions

Concise test instructions on how to verify that your feature works as intended. This should include
changes to the development environment (if applicable) and all commands needed to run your work.

## Screenshot

If applicable (e.g. UI changes), add screenshots to help explain your work.

### CODE REVIEW

**Comment by jumaallan** [comment]
This is still work in progress, so don't review just yet

**Comment by vanshg** [comment]
The reason the names are capitalized on Android are to match the Composable function convention. There is no such convention on Swift afaik. @JubrilO @JNdhlovu Can you chime in here whether this naming scheme is a good practice for Swift?

**Comment by JubrilO** [comment]
@vanshg There is a [convention](https://www.swift.org/documentation/api-design-guidelines/#conventions). 

> Names of types and protocols should are `UpperCamelCase`. Everything else is `lowerCamelCase`.

**Comment by vanshg** [comment]
Right so in that case, I don't think we should merge this PR

**Pull request closed without merging**
